included:

excluded:
- Pods

    
disabled_rules:
- trailing_whitespace
- identifier_name
- cyclomatic_complexity
- function_body_length
- unused_optional_binding

force_cast: warning
line_length: 250
